<?php
/**
 * Created by PhpStorm.
 * User: zuizui
 * Date: 2017/11/13
 * Time: 23:33
 */
namespace app\models;

use Yii;
use yii\base\Model;

class EntryForm extends Model{
    public $name;
    public $email;

    public function rules()
    {
        return [
            [['name','email'],'required'],
            ['email','email']
        ]; // TODO: Change the autogenerated stub
    }
}